## Install Numpy

In [ ]:
!pip install numpy

## Import Numpy

In [ ]:
import numpy as np

## 1. The basics

### Create a Numpy array

In [ ]:
arr = np.empty(shape= (2, 2))
arr

array([[5.e-324, 5.e-324],
       [5.e-324, 0.e+000]])

In [ ]:
a = np.array([1,2,3], dtype='int32')
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
arr = np.linspace(start=0, stop=10, num=10)
arr

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### Get dimension

In [ ]:
print(a.ndim)
print(b.ndim)

1
2


### Get shape

In [ ]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


### Get type

In [ ]:
print(a.dtype)
print(b.dtype)

int32
float64


### Get number of elements

In [ ]:
print(a.size)
print(b.size)

3
6


## 2. Accessing/Changing elements

In [ ]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
c[0,1:-1:2]

array([2, 4, 6])

In [ ]:
c[1,5]

13

### Access a specific element

In [ ]:
# [row, column]

In [ ]:
c[1,2]

10

### Access a specific row/column

In [ ]:
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
c[:, -1]

array([ 7, 14])

### Access elements by steps

In [ ]:
### [start_index : end_index : step_size]
c[1,2:-1:2]

array([10, 12])

### Change elements

In [ ]:
c[1,5] = 1000
print(c)

[[   1    2    3    4    5    6    7]
 [   8    9   10   11   12 1000   14]]


In [ ]:
c[:, 2] = [2000, 3000]
print(c)

[[   1    2 2000    4    5    6    7]
 [   8    9 3000   11   12 1000   14]]


In [ ]:
c[0, 3:-1] = [4000, 5000, 6000]
print(c)

[[   1    2 2000 4000 5000 6000    7]
 [   8    9 3000   11   12 1000   14]]


In [ ]:
print(c)

In [ ]:
c[:,2] = [999, 998]
print(c)

[[   1    2  999 4000 5000 6000    7]
 [   8    9  998   11   12 1000   14]]


In [ ]:
# Example for a 3D array
d = np.array([[[1,2], [3,5]], [[5,6], [7,8]]])
print(d)

[[[1 2]
  [3 5]]

 [[5 6]
  [7 8]]]


In [ ]:
d[0,0,1]

In [ ]:
d.shape

In [ ]:
d.ndim

In [ ]:
d.size

In [ ]:
# To access a 3D array's element, count outside in
d[1,0,0]

In [ ]:
# Change element of a 3D array
d[:,:,1] = 999
print(d)

### Repeat an array

In [ ]:
arr = np.array([[1,3,5,7], [2,4,6,8]])
print(np.repeat(a=arr, repeats=4))
print(np.repeat(a=arr, repeats=4, axis=0))
print(np.repeat(a=arr, repeats=4, axis=1))

### Copy an array

In [ ]:
ori = np.array([24,12,2019])
copied = ori.copy()
copied[-1] = 1903

print(ori)
print(copied)

## 3. Initialize different types of array

### All 1s matrix

In [ ]:
one_matrix = np.ones(shape=(4,5))
print(one_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### All 0s matrix

In [ ]:
zero_matrix = np.zeros(shape=(2,5))
print(zero_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Any number matrix

In [ ]:
ninenine_matrix = np.full(shape=(3,6),fill_value=777, dtype='float32')
print(ninenine_matrix)

[[777. 777. 777. 777. 777. 777.]
 [777. 777. 777. 777. 777. 777.]
 [777. 777. 777. 777. 777. 777.]]


### Any number matrix (full_like)

In [ ]:
blueprint = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(blueprint)

seven_matrix = np.full_like(a=blueprint, fill_value=7)
print(seven_matrix)

another_seven_matrix = np.full(shape=blueprint.shape, fill_value=7)
print(another_seven_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Idenrity matrix

In [ ]:
i_matrix = np.identity(n=5)
print(i_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Random decimal number array

In [ ]:
random_array = np.random.rand(3,4)
print(random_array)

[[0.98087341 0.64973791 0.15220321 0.68581325]
 [0.63771548 0.77607551 0.12918316 0.45604436]
 [0.90335673 0.86302603 0.77914179 0.36061205]]


### Random integer array

In [ ]:
print(np.random.randint(low=-110, high=200, size=(3,6)))

[[ 30  75 163 125 -83 157]
 [175 105 -77  76 176 147]
 [117 148 171   9  70  95]]


## 4. Mathematics & Statistics

### Simple calculations

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array(object=[9,8,7,6,5,4,3,2,1])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2 - 2*b)

[10 10 10 10 10 10 10 10 10]
[-8 -6 -4 -2  0  2  4  6  8]
[ 9 16 21 24 25 24 21 16  9]
[0.11111111 0.25       0.42857143 0.66666667 1.         1.5
 2.33333333 4.         9.        ]
[-17 -12  -5   4  15  28  43  60  79]


### Linear algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.dot(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

### Statistics

In [63]:
stats = np.array([[1,2,3],[4,5,6]])

print(np.min(stats))
print(np.max(stats))
print(np.sum(stats))

1
6
21


In [ ]:
print(np.min(stats, axis=1))
print(np.max(stats, axis=1))

[1 4]
[3 6]


## 5. Reorganizing array

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,-1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Vertically stacking vectors

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack(tup=(v1,v2,v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### Horizontally stacking vectors

In [ ]:
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

np.hstack(tup=(h1,h2,h2,h2))

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8])

## 6. Boolean masking and advanced indexing

In [ ]:
arr = np.random.randint(low=1, high=20, size=(8,5))
print(arr)

[[10  1 18  5  8]
 [ 8  1  7 17  7]
 [ 7  4  5  5 19]
 [ 4 19 15  1  9]
 [12 16  8 19  4]
 [ 8  3  3  3  4]
 [15 16 19  9  7]
 [16  2  7  6 11]]


In [ ]:
bool_mask = arr > 10
print(bool_mask)

[[False False  True False False]
 [False False False  True False]
 [False False False False  True]
 [False  True  True False False]
 [ True  True False  True False]
 [False False False False False]
 [ True  True  True False False]
 [ True False False False  True]]


In [57]:
arr  = np.random.randint(low = 1, high=10, size=(20, 10))
mask  = np.random.randint(low = 1, high=10, size=(10))
print(arr, mask)

[[6 7 5 8 3 1 7 6 7 3]
 [7 8 3 6 4 4 4 4 6 5]
 [7 4 9 5 2 4 6 3 8 8]
 [8 1 2 9 6 1 6 7 7 4]
 [6 9 7 4 6 3 5 6 4 8]
 [1 6 4 8 9 7 8 8 4 1]
 [6 2 9 8 5 8 3 1 5 9]
 [1 9 1 4 7 9 1 6 6 2]
 [8 2 8 7 5 1 8 4 2 9]
 [8 2 7 1 5 3 4 8 9 8]
 [2 9 7 9 6 8 8 1 7 3]
 [3 9 1 2 9 3 1 6 8 8]
 [5 3 5 5 4 6 5 1 7 8]
 [6 2 5 9 5 1 1 2 8 1]
 [6 9 1 2 2 3 6 1 9 3]
 [7 6 5 3 2 9 7 7 6 7]
 [7 4 6 5 3 1 9 8 7 6]
 [9 3 5 4 9 5 8 2 3 3]
 [7 5 4 6 8 6 8 8 4 7]
 [5 9 3 7 2 2 1 6 1 2]] [2 1 4 4 2 8 8 4 4 3]


In [62]:
boolean_mask = mask > 5
arr_2 = arr[:, boolean_mask]
arr_2

array([[-1,  5],
       [-1,  6],
       [ 9,  7],
       [ 7, -1],
       [ 9, -1],
       [ 7,  5],
       [-1, -1],
       [-1, -1],
       [ 6, -1],
       [ 7,  5],
       [ 5,  7],
       [ 5,  9],
       [-1,  7],
       [ 6, -1],
       [-1, -1],
       [-1,  9],
       [ 9,  7],
       [-1,  6],
       [ 6, -1],
       [ 5, -1]])

array([[5, 6, 1],
       [4, 1, 1],
       [3, 2, 6],
       [5, 7, 6],
       [1, 8, 7],
       [1, 1, 6],
       [6, 6, 4],
       [9, 8, 6],
       [4, 7, 3],
       [9, 8, 8],
       [3, 3, 8],
       [3, 8, 4],
       [2, 4, 4],
       [6, 5, 3],
       [8, 7, 9],
       [6, 1, 7],
       [1, 6, 1],
       [8, 7, 7],
       [2, 1, 3],
       [5, 1, 2]])

In [61]:
larger_than_10 = arr[arr > 10]
print(larger_than_10)

[]


In [60]:
b_mask = arr < 5
arr[b_mask] = -1

In [58]:
arr  = np.random.randint(low = 1, high=10, size=(20, 10))

np.transpose(arr)

array([[8, 3, 4, 1, 4, 7, 7, 7, 2, 2, 4, 9, 8, 6, 8, 1, 7, 1, 7, 6],
       [9, 9, 6, 3, 3, 7, 1, 2, 3, 4, 7, 8, 8, 6, 7, 1, 6, 9, 9, 4],
       [7, 9, 1, 8, 4, 3, 6, 3, 3, 8, 9, 9, 6, 2, 7, 4, 2, 6, 4, 9],
       [7, 1, 2, 1, 6, 9, 6, 8, 3, 9, 4, 5, 2, 6, 9, 3, 9, 2, 8, 8],
       [4, 4, 3, 6, 2, 6, 2, 9, 9, 4, 7, 4, 6, 8, 9, 2, 9, 1, 6, 5],
       [2, 3, 9, 7, 9, 7, 2, 1, 6, 7, 5, 5, 1, 6, 1, 2, 9, 2, 6, 5],
       [5, 6, 7, 3, 2, 5, 2, 1, 3, 5, 7, 9, 7, 1, 1, 9, 7, 6, 3, 1],
       [7, 2, 4, 3, 3, 6, 8, 1, 1, 4, 2, 1, 9, 8, 8, 6, 2, 4, 7, 9],
       [8, 1, 1, 5, 9, 3, 9, 2, 1, 4, 2, 4, 2, 2, 3, 6, 4, 2, 8, 7],
       [7, 5, 9, 5, 9, 9, 7, 8, 2, 3, 4, 9, 5, 1, 9, 6, 4, 7, 7, 8]])